platform :ios, '8.0'

target 'Example' do
    use_frameworks!
    pod 'AwesomeUtilities', :path => '../'
end

target 'ExampleTests' do
    use_frameworks!
    pod 'AwesomeUtilities/Tests', :path => '../'
end
